# Site settings
title:          书评
description:    "主要是评论网络小说，配合微信公众号。"
baseurl:        ""
url:            "http://www.commentbook.org"

# Author
author:
  name:         荒岛书生
  url:          www.lidaxiang.cn
  email:        http://lidaxiang0@outlook.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins_dir:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title

# 首页显示的文章分页，每页数量
paginate:       15

# 文章摘要标识符
excerpt_separator: "<!---more--->"

timezone: China/Shanghai
# categories:
#   - sssss
#   - wowww

gems: [jekyll-paginate]